name: ✨Feature Request
description: Request a new feature or enhancement
title: "[FEAT]: <description>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues
  
  - type: textarea
    id: feat-description
    attributes:
      label: Description
      description: A brief description of the feature or enhancement you propose, also include what you tried and what worked.
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.
